import type { ProyeksiAktual, RekeningBank, StatusBudget } from './cashflowData';
export const sum = (values: number[]) => values.reduce((a, b) => a + Number(b || 0), 0);
export const totalProyeksi = (rows: ProyeksiAktual[]) => sum(rows.map((r) => r.proyeksi));
export const totalAktual = (rows: ProyeksiAktual[]) => sum(rows.map((r) => r.aktual));
export const selisihBudget = (proyeksi: number, aktual: number) => proyeksi - aktual;
export const persentaseRealisasi = (proyeksi: number, aktual: number) => proyeksi === 0 ? (aktual > 0 ? 100 : 0) : Math.round((aktual / proyeksi) * 100);
export const statusBudget = (proyeksi: number, aktual: number): StatusBudget => proyeksi === 0 && aktual > 0 ? 'TIDAK DIPROYEKSIKAN' : persentaseRealisasi(proyeksi, aktual) < 80 ? 'AMAN' : persentaseRealisasi(proyeksi, aktual) <= 100 ? 'PERLU PERHATIAN' : 'OVER BUDGET';
export const saldoAkhir = (r: RekeningBank) => r.saldoAwal + r.masuk - r.keluar;
export const totalSaldoSeluruhRekening = (rows: RekeningBank[]) => sum(rows.map(saldoAkhir));
export const totalCashIn = (rows: RekeningBank[]) => sum(rows.map((r) => r.masuk));
export const totalCashOut = (rows: RekeningBank[]) => sum(rows.map((r) => r.keluar));
export const netCashflow = (rows: RekeningBank[]) => totalCashIn(rows) - totalCashOut(rows);
