import { useState } from 'react';
import { categories, type BalanceEntry, type Brand } from '../types';

export function BalanceEntryForm({ brands, onAddBrand, onAddEntry }: { brands: Brand[]; onAddBrand: (name: string, entityName: string) => void; onAddEntry: (brandId: string, entry: Omit<BalanceEntry, 'id'>) => void; }) {
  const [brandName,setBrandName]=useState(''); const [entity,setEntity]=useState(''); const [brandId,setBrandId]=useState(brands[0]?.id ?? '');
  const [entry,setEntry]=useState({ name:'', provider:'BCA', accountNumber:'', category:'Bank' as BalanceEntry['category'], balance:0, note:'' });
  return <div className="grid gap-3 rounded-xl border bg-white p-4 shadow-sm lg:grid-cols-2"><form onSubmit={e=>{e.preventDefault(); if(!brandName.trim()) return alert('Brand/entity wajib diisi'); onAddBrand(brandName.trim(), entity.trim() || brandName.trim()); setBrandName(''); setEntity('');}} className="space-y-2"><h2 className="font-black">Tambah Brand / Entity</h2><input className="input w-full" placeholder="Nama brand/entity" value={brandName} onChange={e=>setBrandName(e.target.value)} required/><input className="input w-full" placeholder="Nama PT/CV/entity legal" value={entity} onChange={e=>setEntity(e.target.value)}/><button className="btn btn-primary">Tambah Brand</button></form>
  <form onSubmit={ev=>{ev.preventDefault(); if(!brandId || !entry.name.trim() || entry.balance < 0) return alert('Lengkapi data rekening dan saldo >= 0'); onAddEntry(brandId, entry); setEntry({...entry,name:'',accountNumber:'',balance:0,note:''});}} className="space-y-2"><h2 className="font-black">Tambah Rekening / Payment</h2><div className="grid grid-cols-2 gap-2"><select className="input" value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input className="input" placeholder="Nama rekening/metode" value={entry.name} onChange={e=>setEntry({...entry,name:e.target.value})} required/><input className="input" placeholder="Bank/provider" value={entry.provider} onChange={e=>setEntry({...entry,provider:e.target.value})}/><input className="input" placeholder="No/kode" value={entry.accountNumber} onChange={e=>setEntry({...entry,accountNumber:e.target.value})}/><select className="input" value={entry.category} onChange={e=>setEntry({...entry,category:e.target.value as BalanceEntry['category']})}>{categories.map(c=><option key={c}>{c}</option>)}</select><input className="input" type="number" min={0} placeholder="Saldo" value={entry.balance} onChange={e=>setEntry({...entry,balance:Number(e.target.value)})}/><input className="input col-span-2" placeholder="Catatan" value={entry.note} onChange={e=>setEntry({...entry,note:e.target.value})}/></div><button className="btn btn-primary">Tambah Rekening</button></form></div>;
}
