import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useAuthUnlock, useDashboardData, useStorageStatus, useUpdateDashboardData } from '../hooks/useDashboardApi';
import { byCategory, createId, formatCurrency, groupBrands, stamp, today, totalBalance, withSettings } from '../lib/format';
import type { BalanceEntry, Category, DashboardData, DeviceStatus } from '../types';
import { categories } from '../types';

const emptyEntry = (brandName: string, entityName?: string): BalanceEntry => ({ id: createId('entry'), brandName, entityName, accountName: 'Rekening Baru', provider: 'BCA', accountCode: '', category: 'Bank', balance: 0, notes: '', displayOrder: Date.now(), isActive: true, updatedAt: stamp() });
const setEntries = (data: DashboardData, entries: BalanceEntry[]): DashboardData => withSettings({ ...data, balanceEntries: entries });
const setDevices = (data: DashboardData, rows: DeviceStatus[]): DashboardData => withSettings({ ...data, deviceStatuses: rows });

export function BalanceDashboard() {
  const storage = useStorageStatus();
  const dashboard = useDashboardData(storage.data?.configured === true);
  const updateData = useUpdateDashboardData();
  const auth = useAuthUnlock();
  const [tab, setTab] = useState<'overview' | 'brands' | 'devices'>('overview');
  const [editMode, setEditMode] = useState(() => sessionStorage.getItem('finance-edit-mode') === 'true');
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [password, setPassword] = useState('');
  const [authError, setAuthError] = useState('');
  const [toast, setToast] = useState('');
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<'Semua' | Category>('Semua');
  const [sort, setSort] = useState<'desc' | 'asc'>('desc');
  const [quickOpen, setQuickOpen] = useState(false);

  const data = dashboard.data;
  const metrics = useMemo(() => {
    const entries = data?.balanceEntries ?? [];
    const groups = groupBrands(entries);
    return { total: totalBalance(entries), groups, brandCount: groups.length, entryCount: entries.filter((e) => e.isActive).length, categoryTotals: byCategory(entries), topBrands: [...groups].sort((a, b) => b.subtotal - a.subtotal).slice(0, 5) };
  }, [data]);
  const filteredGroups = useMemo(() => metrics.groups.map((group) => ({ ...group, entries: group.entries.filter((entry) => `${entry.brandName} ${entry.entityName ?? ''} ${entry.accountName} ${entry.provider} ${entry.accountCode ?? ''}`.toLowerCase().includes(search.toLowerCase()) && (category === 'Semua' || entry.category === category)) })).filter((group) => group.entries.length).sort((a, b) => sort === 'desc' ? b.subtotal - a.subtotal : a.subtotal - b.subtotal), [metrics.groups, search, category, sort]);

  const save = (next: DashboardData, message: string) => updateData.mutate(next, { onSuccess: () => { setToast(message); setTimeout(() => setToast(''), 2500); } });
  const updateEntry = (id: string, patch: Partial<BalanceEntry>) => data && save(setEntries(data, data.balanceEntries.map((entry) => entry.id === id ? { ...entry, ...patch, updatedAt: stamp() } : entry)), 'Perubahan saldo tersimpan ke Vercel Blob.');
  const deleteEntry = (id: string) => data && confirm('Hapus rekening ini?') && save(setEntries(data, data.balanceEntries.filter((entry) => entry.id !== id)), 'Rekening berhasil dihapus.');
  const addEntry = (brandName: string, entityName?: string) => data && save(setEntries(data, [...data.balanceEntries, emptyEntry(brandName, entityName)]), 'Rekening baru ditambahkan.');
  const updateDevice = (id: string, patch: Partial<DeviceStatus>) => data && save(setDevices(data, data.deviceStatuses.map((row) => row.id === id ? { ...row, ...patch, updatedAt: stamp() } : row)), 'Status device tersimpan.');
  const addDevice = () => data && save(setDevices(data, [...data.deviceStatuses, { id: createId('device'), area: 'Area Baru', status: 'OK', number: '', device: '', notes: '', displayOrder: Date.now(), updatedAt: stamp() }]), 'Device ditambahkan.');
  const deleteDevice = (id: string) => data && confirm('Hapus device ini?') && save(setDevices(data, data.deviceStatuses.filter((row) => row.id !== id)), 'Device dihapus.');
  const unlock = async () => { const result = await auth.mutateAsync(password); if (result.ok) { sessionStorage.setItem('finance-edit-mode', 'true'); setEditMode(true); setPasswordOpen(false); setAuthError(''); } else setAuthError('Password belum sesuai. Silakan cek kembali.'); };

  if (storage.isLoading) return <State title="Menyiapkan dashboard" message="Mengecek status Vercel Blob dari server..." />;
  if (storage.data?.configured === false) return <State title="Vercel Blob belum dikonfigurasi" message={storage.data.message ?? 'BLOB_READ_WRITE_TOKEN missing'} />;
  if (dashboard.isLoading) return <State title="Mengambil data saldo" message="Jika file Blob belum ada, sample data akan otomatis digunakan." />;
  if (dashboard.isError || !data) return <State title="Dashboard gagal dimuat" message="API dashboard-data belum merespons normal. Cek Vercel Function logs." />;

  return <main className="min-h-screen bg-slate-100 px-4 py-6 text-slate-900 lg:px-8"><div className="mx-auto max-w-7xl space-y-8">
    {toast && <div className="fixed right-5 top-5 z-50 rounded-2xl bg-emerald-600 px-5 py-3 text-white shadow-xl">{toast}</div>}
    <header className="rounded-[2rem] bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-8 text-white shadow-2xl"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm uppercase tracking-[0.3em] text-emerald-300">Executive Finance Dashboard</p><h1 className="mt-3 text-4xl font-semibold">{data.dashboardSettings.dashboardTitle}</h1><p className="mt-3 text-slate-300">Update {data.dashboardSettings.updateDate} · Last saved {new Date(data.dashboardSettings.lastUpdatedAt).toLocaleString('id-ID')}</p></div><div className="flex flex-wrap gap-3">{editMode && <button className="rounded-full bg-emerald-400 px-4 py-2 text-sm font-bold text-slate-950">Edit Mode Active</button>}<button onClick={() => editMode ? (sessionStorage.removeItem('finance-edit-mode'), setEditMode(false)) : setPasswordOpen(true)} className="rounded-full bg-white/10 px-5 py-2 font-semibold ring-1 ring-white/20 hover:bg-white/20">{editMode ? 'Lock Edit Mode' : 'Unlock Edit Mode'}</button></div></div><div className="mt-10"><p className="text-slate-300">Total All Rekening</p><p className="mt-2 text-5xl font-bold lg:text-7xl">{formatCurrency(metrics.total)}</p></div></header>
    <nav className="flex gap-3 rounded-3xl bg-white p-2 shadow-sm">{[['overview','Overview'],['brands','Brand Details'],['devices','Device Status']].map(([key,label]) => <button key={key} onClick={() => setTab(key as typeof tab)} className={`flex-1 rounded-2xl px-4 py-3 font-semibold ${tab === key ? 'bg-slate-900 text-white' : 'text-slate-500 hover:bg-slate-100'}`}>{label}</button>)}</nav>
    {editMode && <button onClick={() => setQuickOpen(true)} className="rounded-2xl bg-emerald-600 px-5 py-3 font-bold text-white shadow-lg">Quick Update Saldo Hari Ini</button>}
    {tab === 'overview' && <section className="space-y-6"><div className="grid gap-4 md:grid-cols-4">{[['Total All Rekening', metrics.total], ['Jumlah Brand/Entity', metrics.brandCount], ['Jumlah Rekening', metrics.entryCount], ['Tanggal Update', data.dashboardSettings.updateDate]].map(([label,value]) => <div key={label} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{typeof value === 'number' && label === 'Total All Rekening' ? formatCurrency(value) : value}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-3"><Panel title="Top 5 Brand Saldo Terbesar">{metrics.topBrands.map((g) => <Line key={g.brandName} left={`${g.brandName} · ${g.entityName ?? ''}`} right={formatCurrency(g.subtotal)} />)}</Panel><Panel title="Breakdown Kategori">{categories.map((cat) => <Line key={cat} left={cat} right={formatCurrency(metrics.categoryTotals[cat] || 0)} />)}</Panel><Panel title="Device Status Summary"><Line left="Total Device" right={`${data.deviceStatuses.length}`} /><Line left="Perlu Cek" right={`${data.deviceStatuses.filter((d) => d.status.toLowerCase() !== 'ok').length}`} /></Panel></div></section>}
    {tab === 'brands' && <section className="space-y-5"><div className="grid gap-3 rounded-3xl bg-white p-4 shadow-sm md:grid-cols-3"><input className="input" placeholder="Search brand/account/provider/code" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="input" value={category} onChange={(e) => setCategory(e.target.value as 'Semua' | Category)}><option>Semua</option>{categories.map((cat) => <option key={cat}>{cat}</option>)}</select><select className="input" value={sort} onChange={(e) => setSort(e.target.value as 'asc' | 'desc')}><option value="desc">Subtotal terbesar</option><option value="asc">Subtotal terkecil</option></select></div>{filteredGroups.map((group) => <details key={`${group.brandName}-${group.entityName}`} className="rounded-3xl bg-white p-6 shadow-sm" open><summary className="cursor-pointer list-none"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><h2 className="text-2xl font-bold">{group.brandName}</h2><p className="text-slate-500">{group.entityName}</p></div><div className="text-2xl font-bold text-emerald-700">{formatCurrency(group.subtotal)}</div></div></summary><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left text-slate-500"><th>Account</th><th>Provider</th><th>Code</th><th>Category</th><th>Balance</th><th>Notes</th><th></th></tr></thead><tbody>{group.entries.map((entry) => <tr key={entry.id} className="border-t"><Cell edit={editMode} value={entry.accountName} onChange={(v) => updateEntry(entry.id, { accountName: v })} /><Cell edit={editMode} value={entry.provider} onChange={(v) => updateEntry(entry.id, { provider: v })} /><Cell edit={editMode} value={entry.accountCode ?? ''} onChange={(v) => updateEntry(entry.id, { accountCode: v })} /><td className="py-3">{editMode ? <select className="input" value={entry.category} onChange={(e) => updateEntry(entry.id, { category: e.target.value as Category })}>{categories.map((cat) => <option key={cat}>{cat}</option>)}</select> : entry.category}</td><td className="py-3">{editMode ? <input className="input" type="number" value={entry.balance} onChange={(e) => updateEntry(entry.id, { balance: Number(e.target.value) })} /> : formatCurrency(entry.balance)}</td><Cell edit={editMode} value={entry.notes ?? ''} onChange={(v) => updateEntry(entry.id, { notes: v })} /><td>{editMode && <button className="text-rose-600" onClick={() => deleteEntry(entry.id)}>Hapus</button>}</td></tr>)}</tbody></table></div>{editMode && <button onClick={() => addEntry(group.brandName, group.entityName)} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 text-white">Tambah Rekening</button>}</details>)}</section>}
    {tab === 'devices' && <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="text-2xl font-bold">Device Status</h2>{editMode && <button onClick={addDevice} className="rounded-xl bg-slate-900 px-4 py-2 text-white">Tambah Row</button>}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr className="text-left text-slate-500"><th>Area</th><th>Status</th><th>Number</th><th>Device</th><th>Notes</th><th></th></tr></thead><tbody>{data.deviceStatuses.map((row) => <tr key={row.id} className="border-t"><Cell edit={editMode} value={row.area} onChange={(v) => updateDevice(row.id, { area: v })} /><Cell edit={editMode} value={row.status} onChange={(v) => updateDevice(row.id, { status: v })} /><Cell edit={editMode} value={row.number ?? ''} onChange={(v) => updateDevice(row.id, { number: v })} /><Cell edit={editMode} value={row.device ?? ''} onChange={(v) => updateDevice(row.id, { device: v })} /><Cell edit={editMode} value={row.notes ?? ''} onChange={(v) => updateDevice(row.id, { notes: v })} /><td>{editMode && <button className="text-rose-600" onClick={() => deleteDevice(row.id)}>Hapus</button>}</td></tr>)}</tbody></table></div></section>}
    {passwordOpen && <Modal title="Unlock Edit Mode" onClose={() => setPasswordOpen(false)}><input className="input w-full" type="password" autoFocus value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password edit mode" /><button className="mt-4 w-full rounded-2xl bg-slate-900 py-3 font-bold text-white" onClick={unlock}>Unlock</button>{authError && <p className="mt-3 text-sm text-rose-600">{authError}</p>}</Modal>}
    {quickOpen && <Modal title="Quick Update Saldo Hari Ini" onClose={() => setQuickOpen(false)}><div className="max-h-[70vh] overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left"><th>Brand</th><th>Account</th><th>Provider</th><th>Code</th><th>Current Balance</th><th>New Balance</th><th>Notes</th></tr></thead><tbody>{data.balanceEntries.map((entry) => <tr className="border-t" key={entry.id}><td>{entry.brandName}</td><td>{entry.accountName}</td><td>{entry.provider}</td><td>{entry.accountCode}</td><td>{formatCurrency(entry.balance)}</td><td><input className="input" type="number" defaultValue={entry.balance} onBlur={(e) => updateEntry(entry.id, { balance: Number(e.target.value) })} /></td><td><input className="input" defaultValue={entry.notes} onBlur={(e) => updateEntry(entry.id, { notes: e.target.value })} /></td></tr>)}</tbody></table></div><button className="mt-4 rounded-2xl bg-emerald-600 px-5 py-3 font-bold text-white" onClick={() => { data && save(withSettings({ ...data, dashboardSettings: { ...data.dashboardSettings, updateDate: today(), lastUpdatedAt: stamp() } }), 'Quick update selesai.'); setQuickOpen(false); }}>Save</button></Modal>}
  </div></main>;
}
function State({ title, message }: { title: string; message: string }) { return <main className="grid min-h-screen place-items-center bg-slate-100 p-6"><div className="max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-3 text-slate-600">{message}</p></div></main>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="mb-4 text-xl font-bold">{title}</h2><div className="space-y-3">{children}</div></div>; }
function Line({ left, right }: { left: string; right: string }) { return <div className="flex justify-between gap-4 border-b border-slate-100 pb-3"><span className="text-slate-600">{left}</span><strong>{right}</strong></div>; }
function Cell({ edit, value, onChange }: { edit: boolean; value: string; onChange: (value: string) => void }) { return <td className="py-3 pr-3">{edit ? <input className="input" value={value} onChange={(e) => onChange(e.target.value)} /> : value}</td>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-6xl rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-bold">{title}</h2><button onClick={onClose} className="rounded-full bg-slate-100 px-3 py-1">Close</button></div>{children}</div></div>; }
