import { useMemo, useState } from 'react';
import { mutasiBank, proyeksiAktual, rekeningBank, type ProyeksiAktual, type RekeningBank, type StatusBudget } from '../lib/cashflowData';
import { persentaseRealisasi, saldoAkhir, selisihBudget, statusBudget, totalAktual, totalProyeksi, totalSaldoSeluruhRekening } from '../lib/cashflowCalculations';
import { formatCurrency } from '../lib/format';

const menus = ['Dashboard', 'Proyeksi vs Aktual', 'Saldo', 'Mutasi Bank', 'Analisis Over Budget', 'Departemen', 'Data Master', 'Pengaturan'] as const;
type Menu = typeof menus[number];
const fmtDate = (value: string) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const statusClass: Record<StatusBudget, string> = { AMAN: 'bg-emerald-500/15 text-emerald-300 ring-emerald-400/30', 'PERLU PERHATIAN': 'bg-amber-400/15 text-amber-200 ring-amber-300/30', 'OVER BUDGET': 'bg-red-500/15 text-red-300 ring-red-400/30', 'TIDAK DIPROYEKSIKAN': 'bg-coral bg-rose-500/15 text-rose-200 ring-rose-300/30' };

export function BalanceDashboard() {
  const [menu, setMenu] = useState<Menu>('Dashboard');
  const [collapsed, setCollapsed] = useState(false);
  const [toast, setToast] = useState('');
  const metrics = useMemo(() => {
    const proyeksi = totalProyeksi(proyeksiAktual), aktual = totalAktual(proyeksiAktual);
    const over = proyeksiAktual.filter((r) => statusBudget(r.proyeksi, r.aktual) === 'OVER BUDGET');
    return { proyeksi, aktual, selisih: selisihBudget(proyeksi, aktual), persen: persentaseRealisasi(proyeksi, aktual), cashIn: 265439414, cashOut: 206622798, net: 58816616, saldo: totalSaldoSeluruhRekening(rekeningBank), overDept: new Set(over.map((r) => r.departemen)).size };
  }, []);
  const notify = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 2200); };
  return <div className="min-h-screen bg-[#07111F] text-[#F8FAFC]">
    {toast && <div className="fixed right-5 top-5 z-50 rounded-2xl bg-[#14B8A6] px-5 py-3 font-semibold text-slate-950 shadow-xl">{toast}</div>}
    <aside className={`fixed inset-y-0 left-0 z-40 hidden border-r border-white/10 bg-[#0B172A] p-4 transition-all lg:block ${collapsed ? 'w-24' : 'w-72'}`}>
      <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#3B82F6] font-black">FC</div>{!collapsed && <div><p className="font-black">Finance Core</p><p className="text-xs text-[#94A3B8]">Cashflow Control</p></div>}</div><button onClick={() => setCollapsed(!collapsed)} className="rounded-xl bg-white/10 px-3 py-2">{collapsed ? '›' : '‹'}</button></div>
      <nav className="mt-8 space-y-2">{menus.map((m, i) => <button key={m} onClick={() => setMenu(m)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left font-semibold ${menu === m ? 'bg-[#3B82F6] text-white' : 'text-[#94A3B8] hover:bg-white/10 hover:text-white'}`}><span>{['▦','↔','◉','⇅','▲','◌','▤','⚙'][i]}</span>{!collapsed && m}</button>)}</nav>
    </aside>
    <main className={`p-4 transition-all md:p-6 lg:p-8 ${collapsed ? 'lg:ml-24' : 'lg:ml-72'}`}>
      <div className="mb-4 flex gap-2 overflow-x-auto lg:hidden">{menus.map((m) => <button key={m} onClick={() => setMenu(m)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${menu === m ? 'bg-[#3B82F6]' : 'bg-[#111F35] text-[#94A3B8]'}`}>{m}</button>)}</div>
      <Header title={menu} />
      {menu === 'Dashboard' && <Dashboard metrics={metrics} />}
      {menu === 'Proyeksi vs Aktual' && <ProyeksiPage notify={notify} />}
      {menu === 'Saldo' && <SaldoPage />}
      {menu === 'Mutasi Bank' && <MutasiPage notify={notify} />}
      {menu === 'Analisis Over Budget' && <OverBudgetPage />}
      {menu === 'Departemen' && <SimplePage title="Departemen" rows={[...new Set(proyeksiAktual.map(r=>r.departemen))].map(d => [d, formatCurrency(proyeksiAktual.filter(r=>r.departemen===d).reduce((s,r)=>s+r.aktual,0))])} />}
      {menu === 'Data Master' && <SimplePage title="Data Master" rows={rekeningBank.map(r => [`${r.brand} - ${r.bank} ${r.nomor}`, 'Aktif'])} />}
      {menu === 'Pengaturan' && <Settings />}
    </main>
  </div>;
}
function Header({ title }: { title: string }) { return <header className="mb-6 rounded-[2rem] bg-gradient-to-r from-[#111F35] to-[#0B172A] p-6 shadow-2xl"><p className="text-sm uppercase tracking-[0.3em] text-[#14B8A6]">Dashboard Cashflow Profesional</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{title}</h1><div className="mt-5 grid gap-3 md:grid-cols-5">{['Brand','Tahun','Bulan','Minggu','Departemen'].map(x=><select key={x} className="rounded-2xl border border-white/10 bg-[#07111F] px-4 py-3 text-[#F8FAFC]"><option>{x}: Semua</option></select>)}</div></header> }
function Dashboard({ metrics }: { metrics: any }) { return <section className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">{[['Total Saldo Bank',metrics.saldo],['Total Cash In',metrics.cashIn],['Total Cash Out',metrics.cashOut],['Net Cashflow',metrics.net],['Total Proyeksi',metrics.proyeksi],['Total Aktual',metrics.aktual],['Selisih Budget',metrics.selisih],['Persentase Realisasi',`${metrics.persen}%`],['Departemen Over Budget',metrics.overDept]].map(([l,v])=><Kpi key={l} label={String(l)} value={typeof v==='number'?formatCurrency(v):String(v)} danger={l==='Selisih Budget'||l==='Persentase Realisasi'||l==='Departemen Over Budget'} />)}</div>{metrics.aktual > metrics.proyeksi && <div className="rounded-[2rem] border border-red-400/30 bg-red-500/15 p-6 text-red-200"><b>OVER BUDGET</b> — Realisasi lebih besar dari proyeksi sebesar {formatCurrency(Math.abs(metrics.selisih))}.</div>}<Charts /></section> }
function Kpi({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className={`rounded-[1.7rem] bg-[#111F35] p-5 shadow-lg ring-1 ${danger?'ring-red-400/30':'ring-white/10'}`}><p className="text-sm text-[#94A3B8]">{label}</p><p className={`mt-3 text-2xl font-black ${danger?'text-[#FB7185]':'text-white'}`}>{value}</p></div>}
function Charts(){const titles=['Cash In vs Cash Out','Proyeksi vs Aktual','Tren Cashflow Mingguan','Pengeluaran per Departemen','Komposisi Saldo per Bank','Lima Penyebab Over Budget Terbesar'];return <div className="grid gap-5 xl:grid-cols-2">{titles.map((t,i)=><div key={t} className="rounded-[2rem] bg-[#111F35] p-6 ring-1 ring-white/10"><h2 className="text-xl font-bold">{t}</h2><div className="mt-5 space-y-3">{(i<3?['Minggu 1','Minggu 2','Minggu 3','Minggu 4']:proyeksiAktual.slice(0,5).map(r=>r.departemen)).map((x,j)=><Bar key={x+j} label={x} pct={30+((j+i)*17)%65} color={['#3B82F6','#14B8A6','#F4B942','#FB7185'][j%4]} />)}</div></div>)}</div>}
function Bar({label,pct,color}:{label:string;pct:number;color:string}){return <div><div className="mb-1 flex justify-between text-sm text-[#94A3B8]"><span>{label}</span><span>{pct}%</span></div><div className="h-3 rounded-full bg-[#07111F]"><div className="h-3 rounded-full" style={{width:`${pct}%`,background:color}} /></div></div>}
function ProyeksiPage({notify}:{notify:(s:string)=>void}){return <section className="space-y-6"><Table rows={proyeksiAktual}/><div className="flex gap-3"><button onClick={()=>notify('Export Excel berhasil disiapkan.')} className="btn">Export Excel</button><button onClick={()=>notify('Export PDF berhasil disiapkan.')} className="btn">Export PDF</button></div><Charts/></section>}
function Table({rows}:{rows:ProyeksiAktual[]}){return <div className="overflow-x-auto rounded-[2rem] bg-[#111F35] p-4 ring-1 ring-white/10"><table className="w-full min-w-[1050px] text-sm"><thead className="text-left text-[#94A3B8]"><tr>{['Departemen','Jenis Biaya','Kategori','Proyeksi','Aktual','Selisih','Persentase Realisasi','Status','Catatan'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const st=statusBudget(r.proyeksi,r.aktual);return <tr key={r.departemen+r.jenisBiaya} className="border-t border-white/10"><td className="p-3 font-bold">{r.departemen}</td><td className="p-3">{r.jenisBiaya}</td><td className="p-3">{r.kategori}</td><td className="p-3">{formatCurrency(r.proyeksi)}</td><td className="p-3">{formatCurrency(r.aktual)}</td><td className="p-3">{formatCurrency(selisihBudget(r.proyeksi,r.aktual))}</td><td className="p-3">{persentaseRealisasi(r.proyeksi,r.aktual)}%</td><td className="p-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ring-1 ${statusClass[st]}`}>{st}</span></td><td className="p-3 text-[#94A3B8]">{r.catatan}</td></tr>})}</tbody></table></div>}
function SaldoPage(){const total=totalSaldoSeluruhRekening(rekeningBank), high=[...rekeningBank].sort((a,b)=>saldoAkhir(b)-saldoAkhir(a))[0], low=[...rekeningBank].sort((a,b)=>saldoAkhir(a)-saldoAkhir(b))[0];return <section className="space-y-6"><div className="grid gap-4 md:grid-cols-5"><Kpi label="Total Saldo Seluruh Rekening" value={formatCurrency(total)}/><Kpi label="Total Saldo FIN_MAKAN" value={formatCurrency(totalSaldoSeluruhRekening(rekeningBank.filter(r=>r.brand==='FIN_MAKAN')))}/><Kpi label="Total Saldo FIN_MINUM" value={formatCurrency(totalSaldoSeluruhRekening(rekeningBank.filter(r=>r.brand==='FIN_MINUM')))}/><Kpi label="Saldo Tertinggi" value={`${high.bank} ${high.nomor}`}/><Kpi label="Saldo Terendah" value={`${low.bank} ${low.nomor}`}/></div><div className="grid gap-4 lg:grid-cols-3">{rekeningBank.map(r=><BankCard key={r.brand+r.nomor} r={r}/>)}</div><Charts/></section>}
function BankCard({r}:{r:RekeningBank}){const akhir=saldoAkhir(r), warn=akhir<r.saldoMinimum;return <article className={`rounded-[2rem] bg-[#111F35] p-6 ring-1 ${warn?'ring-red-400/40':'ring-white/10'}`}><div className="flex justify-between"><div><p className="text-[#94A3B8]">{r.brand}</p><h3 className="text-2xl font-black">{r.bank} • {r.nomor}</h3></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${warn?'bg-red-500/20 text-red-200':'bg-emerald-500/20 text-emerald-200'}`}>{warn?'SALDO RENDAH':'AMAN'}</span></div>{[['Saldo awal',r.saldoAwal],['Total uang masuk',r.masuk],['Total uang keluar',r.keluar],['Saldo akhir',akhir]].map(([l,v])=><div className="mt-4 flex justify-between border-b border-white/10 pb-2" key={String(l)}><span className="text-[#94A3B8]">{l}</span><b>{formatCurrency(Number(v))}</b></div>)}<p className="mt-4 text-sm text-[#94A3B8]">Update terakhir: {fmtDate(r.updatedAt)}</p></article>}
function MutasiPage({notify}:{notify:(s:string)=>void}){return <section className="space-y-6"><div className="rounded-[2rem] bg-[#111F35] p-6 ring-1 ring-white/10"><h2 className="text-2xl font-bold">Upload Excel Mutasi Bank</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><select className="input-dark"><option>Pilih rekening bank</option>{rekeningBank.map(r=><option key={r.nomor}>{r.bank} {r.nomor}</option>)}</select><input type="file" accept=".xlsx,.xls" className="input-dark"/><button onClick={()=>notify('Preview divalidasi. Tekan Simpan Data untuk konfirmasi.')} className="btn">Validasi Preview</button></div><ol className="mt-5 grid gap-2 text-[#94A3B8] md:grid-cols-2"><li>1. Pilih rekening bank.</li><li>2. Unggah Excel.</li><li>3. Preview data.</li><li>4. Validasi tanggal, nominal, duplikat.</li><li>5. Perbaiki kategori dan departemen.</li><li>6. Simpan setelah konfirmasi.</li></ol><button onClick={()=>notify('Data mutasi tersimpan dan dashboard diperbarui otomatis.')} className="btn mt-5">Simpan Data</button></div><div className="overflow-x-auto rounded-[2rem] bg-[#111F35] p-4 ring-1 ring-white/10"><table className="w-full min-w-[1200px] text-sm"><thead className="text-left text-[#94A3B8]"><tr>{['Tanggal','Bank','Nomor Rekening','Deskripsi Transaksi','Nomor Referensi','Debit','Kredit','Saldo','Departemen','Kategori','Masuk Proyeksi','Catatan'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{mutasiBank.map(m=><tr className="border-t border-white/10" key={m.referensi}><td className="p-3">{m.tanggal}</td><td className="p-3">{m.bank}</td><td className="p-3">{m.nomorRekening}</td><td className="p-3">{m.deskripsi}</td><td className="p-3">{m.referensi}</td><td className="p-3">{formatCurrency(m.debit)}</td><td className="p-3">{formatCurrency(m.kredit)}</td><td className="p-3">{formatCurrency(m.saldo)}</td><td className="p-3">{m.departemen}</td><td className="p-3">{m.kategori}</td><td className="p-3">{m.masukProyeksi?'Ya':'Tidak'}</td><td className="p-3">{m.catatan}</td></tr>)}</tbody></table></div></section>}
function OverBudgetPage(){const rows=proyeksiAktual.filter(r=>statusBudget(r.proyeksi,r.aktual)==='OVER BUDGET');return <section className="space-y-6"><div className="grid gap-4 md:grid-cols-4"><Kpi label="Selisih Terbesar" value={formatCurrency(Math.min(...rows.map(r=>selisihBudget(r.proyeksi,r.aktual))))} danger/><Kpi label="Kategori Aktual Terbesar" value="COGS"/><Kpi label="Transaksi Tanpa Proyeksi" value="1" danger/><Kpi label="Persentase Over Budget" value="41%" danger/></div><div className="overflow-x-auto rounded-[2rem] bg-[#111F35] p-4 ring-1 ring-white/10"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-[#94A3B8]"><tr>{['Departemen','Proyeksi','Aktual','Selisih','Penyebab Utama','Rekomendasi','Status Tindak Lanjut'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-white/10" key={r.departemen}><td className="p-3 font-bold">{r.departemen}</td><td className="p-3">{formatCurrency(r.proyeksi)}</td><td className="p-3">{formatCurrency(r.aktual)}</td><td className="p-3 text-[#FB7185]">{formatCurrency(selisihBudget(r.proyeksi,r.aktual))}</td><td className="p-3">{r.catatan}</td><td className="p-3">Review approval dan kunci budget mingguan.</td><td className="p-3">Dalam tindak lanjut</td></tr>)}</tbody></table></div></section>}
function SimplePage({title,rows}:{title:string;rows:string[][]}){return <div className="rounded-[2rem] bg-[#111F35] p-6 ring-1 ring-white/10"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-5 grid gap-3">{rows.length?rows.map((r,i)=><div key={i} className="flex justify-between rounded-2xl bg-[#07111F] p-4"><span>{r[0]}</span><b>{r[1]}</b></div>):<p className="text-[#94A3B8]">Belum ada data.</p>}</div></div>}
function Settings(){
  const [master, setMaster] = useState(rekeningBank.map((r) => ({ ...r })));
  const [savedAt, setSavedAt] = useState('Belum ada perubahan tersimpan');
  const updateMaster = (index: number, patch: Partial<RekeningBank>) => setMaster((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const addMaster = () => setMaster((rows) => [...rows, { brand: 'FIN_MAKAN', bank: 'Bank Baru', nomor: '000', saldoAwal: 0, masuk: 0, keluar: 0, saldoMinimum: 0, updatedAt: new Date().toISOString() }]);
  const deleteMaster = (index: number) => setMaster((rows) => rows.filter((_, rowIndex) => rowIndex !== index));
  return <div className="space-y-6"><div className="rounded-[2rem] bg-[#111F35] p-6 ring-1 ring-white/10"><h2 className="text-2xl font-bold">Pengaturan</h2><p className="mt-3 text-[#94A3B8]">Versi frontend stabil menggunakan dummy data terpusat. Data master di bawah dapat diedit untuk simulasi sebelum integrasi Excel/API dibuat.</p><div className="mt-5 rounded-2xl bg-[#07111F] p-4">Status aplikasi: Siap monitoring</div></div>
    <section className="rounded-[2rem] bg-[#111F35] p-6 ring-1 ring-white/10"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[0.25em] text-[#14B8A6]">Data Master</p><h3 className="mt-1 text-2xl font-black">Rekening Bank Editable</h3><p className="mt-2 text-sm text-[#94A3B8]">Edit brand, bank, nomor rekening, saldo minimum, dan komponen saldo. Perubahan tersimpan sementara di layar pengaturan.</p></div><button onClick={addMaster} className="btn">Tambah Rekening</button></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="text-left text-[#94A3B8]"><tr>{['Brand','Bank','Nomor','Saldo Awal','Uang Masuk','Uang Keluar','Saldo Minimum','Saldo Akhir','Aksi'].map((h)=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{master.map((row,index)=><tr key={`${row.brand}-${row.bank}-${row.nomor}-${index}`} className="border-t border-white/10"><td className="p-3"><select className="input-dark" value={row.brand} onChange={(e)=>updateMaster(index,{brand:e.target.value as RekeningBank['brand']})}><option>FIN_MAKAN</option><option>FIN_MINUM</option></select></td><td className="p-3"><input className="input-dark" value={row.bank} onChange={(e)=>updateMaster(index,{bank:e.target.value})}/></td><td className="p-3"><input className="input-dark" value={row.nomor} onChange={(e)=>updateMaster(index,{nomor:e.target.value})}/></td>{(['saldoAwal','masuk','keluar','saldoMinimum'] as const).map((field)=><td className="p-3" key={field}><input className="input-dark w-36" type="number" value={row[field]} onChange={(e)=>updateMaster(index,{[field]:Number(e.target.value)} as Partial<RekeningBank>)}/></td>)}<td className="p-3 font-bold text-[#22C55E]">{formatCurrency(saldoAkhir(row))}</td><td className="p-3"><button onClick={()=>deleteMaster(index)} className="rounded-xl bg-red-500/15 px-3 py-2 font-bold text-red-200 ring-1 ring-red-400/30">Hapus</button></td></tr>)}</tbody></table></div>
      <div className="mt-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><p className="text-sm text-[#94A3B8]">{savedAt}</p><button onClick={()=>setSavedAt(`Perubahan data master tersimpan sementara pada ${new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}`)} className="btn">Simpan Perubahan</button></div></section></div>}

