import type { Brand } from '../types';
import { calculateBrandSubtotal, formatRupiah } from '../lib/format';

export function BrandBalanceCard({ brand, onBalanceChange, onDeleteEntry, onDeleteBrand }: { brand: Brand; onBalanceChange: (entryId: string, balance: number) => void; onDeleteEntry: (entryId: string) => void; onDeleteBrand: () => void; }) {
  return <section className="overflow-hidden rounded-xl border-2 border-slate-300 bg-white shadow-sm">
    <div className={`bg-gradient-to-r ${brand.color} px-3 py-2 text-white`}><div className="flex justify-between gap-2"><div><h3 className="font-black uppercase tracking-wide">{brand.name}</h3><p className="text-xs opacity-90">{brand.entityName}</p></div><button onClick={onDeleteBrand} className="text-xs underline" title="Hapus jika kosong">hapus brand</button></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[520px] border-collapse text-xs"><thead className="bg-slate-100"><tr><th className="sheet-cell text-left">Rekening / Metode</th><th className="sheet-cell">Bank</th><th className="sheet-cell">No/Kode</th><th className="sheet-cell">Kategori</th><th className="sheet-cell text-right">Saldo</th><th className="sheet-cell">Aksi</th></tr></thead><tbody>{brand.entries.map(e => <tr key={e.id} className="hover:bg-yellow-50"><td className="sheet-cell"><b>{e.name}</b><div className="text-[10px] text-slate-500">{e.note}</div></td><td className="sheet-cell text-center">{e.provider}</td><td className="sheet-cell text-center">{e.accountNumber}</td><td className="sheet-cell text-center">{e.category}</td><td className="sheet-cell text-right"><input className="w-32 rounded border px-2 py-1 text-right" type="number" min={0} value={e.balance} onChange={ev => onBalanceChange(e.id, Math.max(0, Number(ev.target.value)))} /><div className="font-semibold">{formatRupiah(e.balance)}</div></td><td className="sheet-cell text-center"><button className="text-red-600 underline" onClick={() => onDeleteEntry(e.id)}>hapus</button></td></tr>)}</tbody><tfoot><tr className="bg-slate-900 text-white"><td className="sheet-cell font-black" colSpan={4}>SUBTOTAL {brand.name}</td><td className="sheet-cell text-right font-black">{formatRupiah(calculateBrandSubtotal(brand))}</td><td className="sheet-cell" /></tr></tfoot></table></div>
  </section>;
}
